# ref: https://mise.jdx.dev/configuration.html
#:schema https://mise.jdx.dev/schema/mise.json

[tools]
bun = "1.2.13"
node = "24.1.0"
"npm:semantic-release" = "24.2.4"
biome = "1.9.4"
actionlint = "1.7.7"
# required for actionlint
shellcheck = "0.10.0"
ghalint = "1.4.0"
pinact = "3.1.2"
taplo = "0.9.3"
yamlfmt = "0.16.0"
# cspell:ignore pipx
# required for pipx backend
uv = "0.7.6"
yamllint = "1.37.1"
"npm:cspell" = "9.0.2"
lychee = "0.18.1"
typos = "1.32.0"
"npm:ignore-sync" = "8.0.0"
"npm:jschema-validator" = "1.0.15"

[settings]
experimental = true

[settings.npm]
bun = true

[task_config]
includes = ["tasks.toml"]

[hooks]
postinstall = """
{% if env.CI is undefined %}
  mise run buni
{% endif %}
"""
