# ref: https://mise.jdx.dev/configuration.html
#:schema https://mise.jdx.dev/schema/mise.json

[tools]
bun = "1.2.17"
node = "24.3.0"
"npm:semantic-release" = "24.2.5"
biome = "1.9.4"
actionlint = "1.7.7"
# required for actionlint
shellcheck = "0.10.0"
ghalint = "1.5.1"
pinact = "3.3.0"
taplo = "0.10.0"
yamlfmt = "0.17.2"
# cspell:ignore pipx
# required for pipx backend
uv = "0.7.14"
yamllint = "1.37.1"
"npm:cspell" = "9.1.2"
lychee = "0.19.1"
typos = "1.33.1"
"npm:ignore-sync" = "8.0.0"
"npm:jschema-validator" = "1.0.16"

[settings]
experimental = true

[settings.npm]
bun = true

[task_config]
includes = ["tasks.toml"]

[hooks]
postinstall = """
{% if env.CI is undefined %}
  mise run buni
{% endif %}
"""
