# ref: https://mise.jdx.dev/configuration.html
#:schema https://mise.jdx.dev/schema/mise.json

min_version = "2025.3.3"

[tools]
bun = "1.2.5"
node = "23.10.0"
"npm:semantic-release" = "24.2.3"
biome = "1.9.4"
actionlint = "1.7.7"
# required for actionlint
shellcheck = "0.10.0"
"aqua:suzuki-shunsuke/ghalint" = "1.2.3" # cspell:ignore shunsuke
"aqua:suzuki-shunsuke/pinact" = "1.4.0"
taplo = "0.9.3"
yamlfmt = "0.16.0"
yamllint = "1.36.2"
"npm:cspell" = "8.17.5"
lychee = "0.18.1"
typos = "1.30.2"
"npm:ignore-sync" = "8.0.0"
"npm:jschema-validator" = "1.0.11"

[settings]
experimental = true
disable_backends = [
	# cspell:ignore pipx
	# disable pipx backend not to require pipx/uv
	"pipx",
]

[settings.npm]
bun = true

[task_config]
includes = ["tasks.toml"]

[hooks]
postinstall = """
{% if env.CI is undefined %}
  mise run buni
{% endif %}
"""
