# ref: https://mise.jdx.dev/tasks/
#:schema https://mise.jdx.dev/schema/mise-task.json

[test]
run = "bun test"
description = "Run tests."

["test:update-snapshots"]
run = "bun test --update-snapshots"
description = "Update test snapshots."

[check]
usage = '''
flag "--lint" help="Run hk check instead of fix"
'''
run = "hk {% if usage.lint %}check{% else %}fix{% endif %} --all --no-progress --no-fail-fast"
description = "Run hk linters and formatters."
